name: scrapecast
description: Scrapes designated websites for data, and publishes a podcast rss feed.
version: 0.0.1
homepage: https://reformatus.github.io/crawlcast

environment:
  sdk: '>=2.16.0-80.1.beta <3.0.0'

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  equatable: ^2.0.3
  html: ^0.15.0
  intl: ^0.17.0
  web_scraper: ^0.1.4
  xml: ^5.3.1
