name: ScrapeCast CRON Run

on:
  schedule:
    - cron: '20 8-21 * * 0,1'
    - cron: '20 8,12,16,21 * * 2-6'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: szenius/set-timezone@v2.0
        with:
            timezoneLinux: "Europe/Budapest"
            
      - uses: actions/checkout@v4

      - name: Git Config
        run: |
          git config user.name "ScrapeCast"
          git config user.email "example@example.com"

      - name: Run
        run: ./bin/scrapecast.exe

      - name: Publish update
        run: |
          git add docs
          git add data
          git add bin/scrapecast.exe
          git commit -m "Publish changes"
          git push origin master
