name: ScrapeCast CRON Run

on:
  schedule:
    - cron: '30 4,12,20 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Git Config
        run: |
          git config user.name "ScrapeCast"
          git config user.email "example@example.com"

      - name: Run
        run: ./bin/scrapecast.exe

      - name: Publish update
        run: |
          git add docs/index.md
          git add docs/krek.rss
          git add data/krek-data.json
          git add bin/scrapecast.exe
          git commit -m "Publish changes"
          git push origin master