name: ScrapeCast CRON Run

on:
  schedule:
    - cron: '30 6,8,10,12,14,16,18,20,22 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: szenius/set-timezone@v1.0
        with:
            timezoneLinux: "Europe/Budapest"
            
      - uses: actions/checkout@v2

      - name: Git Config
        run: |
          git config user.name "ScrapeCast"
          git config user.email "example@example.com"

      - name: Run
        run: ./bin/scrapecast.exe

      - name: Publish update
        run: |
          git add docs
          git add data
          git add bin/scrapecast.exe
          git commit -m "Publish changes"
          git push origin master
